### ISSUE TITLE
jumping for a long time hurts the bot

### ISSUE THREAD

**Issue by vogonistic** [andrewrk/mineflayer#114]
Can be reproduced by leaving `bot.setControlState('jump', true)` on until the bot dies with the text: `bot hit the ground too hard`

**Comment by rom1504** [comment]
I just checked, this is still an issue, setting bot.setControlState('jump', true); : 
* make the bot not touch the ground : I don't know whether this is wrong or not
* after like 30s the bot die with "fell from a high place"

**Comment by rom1504** [comment]
do we use that http://minecraft.gamepedia.com/The_Player#Movement 
"The maximum height a player can jump without the "jump boost" effect is about 1.252 blocks." 
?

**Comment by rom1504** [comment]
Also see http://minecraft.gamepedia.com/Effect

**Comment by roblabla** [comment]
I don't think we support status effects. It was added with 1.7, with the beacons, IIRC.

**Comment by rom1504** [comment]
Yeah, but we should still jump only a maximum of 1.252 blocks. I'm pretty sure physics.js jump implementation doesn't do that.
