### ISSUE TITLE
Problems with craft

### ISSUE THREAD

**Issue by rom1504** [andrewrk/mineflayer#144]
Most of the time craft works but sometime it doesn't.
Here is a test case that should work and doesn't : 
1) start the inventory example
2) give the bot 64 log
3) say craft 2 wood
4) error making wood
in the console : "Error: Server rejected transaction."

I hope this can help solve the problem.

**Comment by rom1504** [comment]
Almost working now : 
* crafting with a crafting table works
* without it doesn't
* need some more testing

**Comment by roblabla** [comment]
I'll bet crafting without crafting table fails because the position of the "crafting table" in the inventory changed in 1.8.

**Comment by rom1504** [comment]
So I just tested this : 
* start the inventory.js bot
* empty its inventory with list and toss
* give the bot 64 log
* add a console.log in clickWindow to see what slot is clicked
* say craft 1 wood

I get this : 
```
36
4
9
0
10
```

According to http://wiki.vg/Inventory#Inventory , it should be : 
* 36 : takethe log
* 4 : put it in one slot of the craft grid
* 0 : take the resulting item
* 9 : put it in the inventory 
* 4 : take the log in the craft grid
* 10 : put it in the inventory

**Comment by rom1504** [comment]
so, it starts being wrong after the 4.
This happens here https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/inventory.js#L540
So there must be something wrong at that point

**Comment by rom1504** [comment]
Yet the second craft always fails on the right click, even if the bot start with the same initials conditions.

**Comment by rom1504** [comment]
After crafting console.log(bot.inventory); says the bot has
* 1 log on 4
* 63 log on 9
* 4 wood on 10

that 1 log on 4 is wrong

**Comment by rom1504** [comment]
It seems the same problem happen with the crafting table. Except the crafting table get closed so probably the item fall on the floor and the bot get them so it seems to work (but it doesn't really).

So it seems the problem is that the crafting grid is not emptied : the used items are still there.

**Comment by rom1504** [comment]
Indeed it now works :)

**Comment by SinanAkkoyun** [comment]
How do you guys craft with a crafting table?
