### ISSUE TITLE
Inventory Manipulation

### ISSUE THREAD

**Issue by Philipp15b** [andrewrk/mineflayer#156]
Is it possible with mineflayer to manipulate inventories? In my case, that would be just moving an item from the inventory into the quickbar. Some manipulation is already implemented for furnaces and chests it seems, but not inventories.

**Comment by rom1504** [comment]
A few more functions are now available https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/inventory.js#L416 (the original reason is they are the only one needed from inventory.js in chest.js,furnace.js,dispenser.js,...). Would adding some of these functions to doc/api.md solve that issue ?
