### ISSUE TITLE
Physics Engine and Minecraft Engine differ in interpreting y axis

### ISSUE THREAD

**Issue by nevercast** [andrewrk/mineflayer#174]
The y axis components in position packets in MC are of the Eye height, but because the physics engine just sends the y position, it is sending the foot position. This causes an illegal stance if you're successfully connected, or prevents you from successfully connecting if you don't send a correct packet to begin with.

The reason that the 1.7 bot was unable to navigate was because of this check on the server:
https://github.com/Bukkit/mc-dev/blob/master/net/minecraft/server/PlayerConnection.java#L94-L99

Because the stance was not correct the y axis didn't match what the server told us, so the server was never marking us as 'ready'
(Still at loading screen state is assumed when CheckPosition is false)

Currently navigation is working in the 1.7 feature branch on my repo, which is currently PR'd to @roblabla (https://github.com/roblabla/mineflayer/pull/2) so that it can be part of the PR to this repo. (https://github.com/andrewrk/mineflayer/pull/173)

The only reason I put this issue here is to bring attention to this issue and open discussion about how we should fix it.

Lines of concern regarding the current fix are here: https://github.com/nevercast/mineflayer/blob/feature-1.7/lib/plugins/physics.js#L328-L339

**Comment by rom1504** [comment]
This is now "fixed" by the fact that the server sends the foot position in 1.8. (see d5d362c9f0599ccff00cfbf822334362bb544036 )
So is that issue fixed ?

**Comment by roblabla** [comment]
Well, the client is still flying in the air. I'll close this when the physics engine starts working again :P

**Comment by rom1504** [comment]
Ok :)

**Comment by rom1504** [comment]
I think that issue is done ? (well of course the enums are not up to date, so there may be problem with some blocks but I don't think it concerns this issue)

**Comment by roblabla** [comment]
Yup, the enums not being up to date isn't part of this issue. Closing !
