### ISSUE TITLE
Ensure all examples work before 1.1.0 is released

### ISSUE THREAD

**Issue by nevercast** [andrewrk/mineflayer#180]
All examples should be tested to be 100% functional before we tag for 1.1.0.

- [x] [Chatterbox](https://github.com/andrewrk/mineflayer/blob/master/examples/chatterbox.js)
- [x] [Chest](https://github.com/andrewrk/mineflayer/blob/master/examples/chest.js)
- [x] [Digger](https://github.com/andrewrk/mineflayer/blob/master/examples/digger.js)
- [x] [Echo](https://github.com/andrewrk/mineflayer/blob/master/examples/echo.js)
- [x] [Graffiti](https://github.com/andrewrk/mineflayer/blob/master/examples/graffiti.js)
- [x] [Inventory](https://github.com/andrewrk/mineflayer/blob/master/examples/inventory.js)
- [x] [Jumper](https://github.com/andrewrk/mineflayer/blob/master/examples/jumper.js)
- [x] [Quitter](https://github.com/andrewrk/mineflayer/blob/master/examples/quitter.js)
- [x] [Sleeper](https://github.com/andrewrk/mineflayer/blob/master/examples/sleeper.js)

Also the test by running `npm test`
- [x] [Test](https://github.com/andrewrk/mineflayer/blob/master/test/test.js)

**Comment by rom1504** [comment]
So : 
* Echo now works
* Digger, ChatterBox and Jumper are starting to work a bit : 
** Digger can now dig (but the bot fly through the air)
** Chatterbox correctly display the name of the connected players
** Jumper doesn't crash anymore

The rest is still totally untested so probably crashing and broken.

**Comment by rom1504** [comment]
Chatterbox now works !

* Jumper refuse to make the bot move forward
* the bot is flying
* the inventory is broken

**Comment by rom1504** [comment]
Quitter now works, most of jumper.js now works : 
* [x] jump
* [x] forward
* [x] back
* [x] left
* [x] right
* [x] stop
* [x] tp
* [x] spawn
* [x] pos
* [x] yp
* [ ] sprint
* [ ] attack
* [ ] mount
* [ ] dismount

Digger : 
* [x] dig
* [ ] build
* [ ] list
* [ ] dirt

**Comment by rom1504** [comment]
ok digger works,
Inventory : 
* [x] list
* [x] look
* [x] toss
* [x] equip
* [x] unequip
* [x] food
* [x] health
* [x] difficulty
* [ ] use
* [ ] stop
* [ ] craft

**Comment by rom1504** [comment]
Sleeper now works.

**Comment by rom1504** [comment]
So, I fixed reading a block in graffiti.js.
Updating is not implemented (must be done after placing a block).
Paintings are not in the block.json enum, are they blocks ?

I think we need to know what's the purpose of graffiti.js before calling it fixed.

**Comment by rom1504** [comment]
So dismount still doesn't work, not sure how to do it, wiki.vg says nothing about that.

**Comment by rom1504** [comment]
sprint is fixed
only dismount left in jumper.js

**Comment by rom1504** [comment]
Ok last example, chest.js : 
* [x] Chest
* [ ] furnace
* [ ] dispenser
* [ ] enchant

**Comment by rom1504** [comment]
Enchant is broken, and I don't really understand the enchant table (I never used it in the game), so I'm going to let that for later.

**Comment by rom1504** [comment]
https://github.com/andrewrk/mineflayer/blob/master/test/test.js is completely broken except for the chat test.

It's needed to adapt the changed packets in there (at least)

**Comment by rom1504** [comment]
test.js : 
* [x] chat
* [x] entity effects 
* [ ] blockAt
* [ ] gravity + land on solid block + jump
* [x] sets players[player].entity to null upon despawn

**Comment by rom1504** [comment]
I don't know how to fix the map chunk format there https://github.com/andrewrk/mineflayer/blob/master/test/test.js#L83

@roblabla maybe you'd know ?

**Comment by deathcap** [comment]
@rom1504 analogous change to https://github.com/andrewrk/mineflayer/commit/dbe6143b0fd10793b0acd29d6e0614be19e5e3b2

**Comment by rom1504** [comment]
I don't understand the chunk format enough to fix this I'm afraid... I bet it doesn't need a lot of changes though, see there https://github.com/andrewrk/mineflayer/blob/master/test/test.js#L73

**Comment by rom1504** [comment]
Should it still be using zlib ?

**Comment by roblabla** [comment]
Nope. compression is now handled on the protocol level

**Comment by rom1504** [comment]
just the offset to fix now https://github.com/andrewrk/mineflayer/blob/master/test/test.js#L84

**Comment by rom1504** [comment]
I'm going to consider test.js (now internalTest.js) working since the remaining test is skipped (https://github.com/andrewrk/mineflayer/blob/master/test/internalTest.js#L72) and is anyway tested better in externalTest.js

**Comment by rom1504** [comment]
dismount done :)

**Comment by rom1504** [comment]
A painting is an entity, see how that applies to graffiti.js

**Comment by rom1504** [comment]
see http://minecraft.gamepedia.com/Data_values/Entity_IDs + https://github.com/andrewrk/mineflayer/issues/207

**Comment by rom1504** [comment]
e15388bca80ae3387c48188d7b8bebff8961218a fix paintings.

**Comment by rom1504** [comment]
Updating a sign is not implemented but graffiti.js is not trying to do it (https://github.com/andrewrk/mineflayer/issues/180#issuecomment-84521477) so let's consider graffiti.js working.

**Comment by rom1504** [comment]
7304a6cce022fb9f9d27d0b5b22069132ceb389b starts working on fixing enchant, but it still doesn't quite work. What's broken : 
* it seems the slots positions aren't quite correct : put doesn't work every time
* enchant 0 doesn't work

If it worked it would be : 
* enchant -> display what's in the enchantment table
* put swordDiamond -> put a diamond sword in the enchantment table and tell use what our enchantment choices are
* enchant 0 -> do the enchantment and tell use what happens

**Comment by rom1504** [comment]
might be related with the facts that QUICK_BAR_START (https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/inventory.js#L240) and INVENTORY_SLOT_COUNT aren't actually constants.

**Comment by rom1504** [comment]
Since 1.8 enchanting need to put lapis on the enchantment table (http://minecraft.gamepedia.com/Enchanting). This is currently not handled at all by mineflayer and is probably (part) of the problem.

**Comment by rom1504** [comment]
INVENTORY_SLOT_COUNT is actually a constant.

**Comment by rom1504** [comment]
bot.inventory should probably be a function or something, and use the inventorySlotStart of each window

**Comment by rom1504** [comment]
The idea is : only one window can ever be open at the same time, so instead of bot.inventory, maybe a bot.currentWindow would make more sense (or for bot.inventory to be bot.currentWindow)

**Comment by rom1504** [comment]
Enchant is fixed. Issue solved :)
