### ISSUE TITLE
Entities disappearing

### ISSUE THREAD

**Issue by nevercast** [andrewrk/mineflayer#181]
> Sometimes, generally after teleporting, entities are removed from the entity list when they shouldn't be.
@roblabla 

Not noticed this myself, more testing needs to be done because this is a severe bug imo.

**Comment by rom1504** [comment]
How can we test this ?

**Comment by rom1504** [comment]
I don't know how to reproduce this. Maybe it should be closed until we can reproduce it ?
Anyway, I haven't noticed this when testing bots, and this is not a big problem, so removing it from the milestone.

**Comment by rom1504** [comment]
Can't reproduce.
