### ISSUE TITLE
Doesn't support 1.7.6

### ISSUE THREAD

**Issue by thiecec** [andrewrk/mineflayer#184]
Would be great if it supported 1.7.6, as https://github.com/andrewrk/node-minecraft-protocol does.

**Comment by deathcap** [comment]
`master` is now targeting 1.8.3. Should we close this since a newer version is (in-progress) supported, or keep open for the (remote, but appealing) possibility of multi-version protocol support? (1.8+1.7,etc.)

**Comment by roblabla** [comment]
For talk about 1.8 support, #198. For talk about multi-protocol support, #199.
