### ISSUE TITLE
Issues running bot

### ISSUE THREAD

**Issue by demipixel** [andrewrk/mineflayer#187]
Alright, so often I've been getting: 

>> node echo.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

Just by using an example file or something like that.
When I run my own server, nothing happens (It looks like it has run and then just ends, prompting me for a new terminal line).

Lastly, if I try to connect to any other server with a username (I assume thats email for minecraft.net login?) and password, it gives the same error as above.

**Comment by rom1504** [comment]
The echo example is now fixed in 1.8, I guess this issue can be closed ?
