### ISSUE TITLE
Missing Some 1.7 Blocks/Items

### ISSUE THREAD

**Issue by NerdYouDontKnow** [andrewrk/mineflayer#189]
Block ids 172 and 159 need to be added.

http://minecraft.gamepedia.com/Hardened_Clay

As well as many more.

Is the JSON file with all the blocks and items coming from somewhere else? It seems like a great resource, and google doesn't come up with much for "minecraft items JSON". If it is being maintained purely here, it should be published elsewhere also since it it such a great resource.

**Comment by deathcap** [comment]
Looks like this was handled (up to 1.8) by https://github.com/andrewrk/mineflayer/pull/227 and https://github.com/andrewrk/mineflayer/pull/230? I didn't get around to updating 1.8 Burger for item/block enum but this manual updating ought to work fine for now (but if anyone wants to help out with https://github.com/mcdevs/Burger/pull/12 I wouldn't mind =p not sure if/when I'll get to it).

Also relevant: https://github.com/andrewrk/mineflayer/issues/229

**Comment by rom1504** [comment]
That data is now in https://github.com/PrismarineJS/minecraft-data , what should be done about this issue ?
It's not 100% solved since we still don't have an automatic process to extract the data but that should be handled in  https://github.com/PrismarineJS/minecraft-data

**Comment by rom1504** [comment]
I'm trying to extract this kind of information from the wiki https://github.com/PrismarineJS/minecraft-data/issues/8
If someone ( @deathcap ?) wants to continue working on extraction using burger, please add an issue / a pull request to https://github.com/PrismarineJS/minecraft-data

closing this issue.
