### ISSUE TITLE
All example programs crash

### ISSUE THREAD

**Issue by Plazmaz** [andrewrk/mineflayer#192]
All the example programs seem to crash as soon as I launch them. I'm currently running a local server on the default port. There is no console output from the program or from the server. The server is Bukkit and I'm running Minecraft 1.7.10. I unfortunately don't have a way to get any extra debug info, due to the lack of console output. There's a few second delay after the program is launched before it crashes.

**Comment by roblabla** [comment]
Closing this, #198 for 1.8-support discussion and #193 for discussion about the current state of the project.
