### ISSUE TITLE
Is this project still maintained? 

### ISSUE THREAD

**Issue by thiecec** [andrewrk/mineflayer#193]
If so, which versions are currently supported? Which versions are planned to be supported?

If not, can I be added as a maintainer? I understand this project depends on a dead dependency, and would be happy to have a go at reworking it to work without that.

**Comment by Corgano** [comment]
Node-minecraft-protocol is updated to 1.8, so now all that remains is updating burger OR updating all the block, item, biome, etc definitions by hand.

**Comment by andrewrk** [comment]
There's a lot more to do than that. I think basically the entire module needs to be rewritten at this point, or at least re-evaluated.

**Comment by deathcap** [comment]
I think its somewhat salvageable, there's a lot of good code in mineflayer still applicable. Started updating Burger https://github.com/mcdevs/Burger/pull/12 but still a ways to go, it may be better to find another means to extract the block and item data (a runtime plugin to iterate Blocks and Items? may be easier than trudging through bytecode)

**Comment by roblabla** [comment]
@andrewrk I've seen quite a lot of work in updating this project to 1.8, and it's pretty successful (we're close to having the digger example working). Mineflayer's API is actually high-enough level that we can easily implement the changes without breaking much. 

@deathcap a forge or bukkit plugin would be a great way to deal with this, now that you mention it. Much easier than dealing with the bytecode :P

**Comment by andrewrk** [comment]
@roblabla great, I hope it works out :-)

**Comment by roblabla** [comment]
@andrewrk @rom1504 should be getting commit access to mineflayer. He's a major contributor to mineflayer right now, and has been contributing a great deal of time patching it up for 1.8.

**Comment by andrewrk** [comment]
done. nice work, @rom1504

**Comment by rom1504** [comment]
oh, thanks

**Comment by rom1504** [comment]
So this project is now maintained again, sometime soon we'll have a 1.1.0 release on npm.
