### ISSUE TITLE
Adding argv parameters in the examples

### ISSUE THREAD

**Issue by rom1504** [andrewrk/mineflayer#204]
Currently bots in the examples are created with
```js
var bot = mineflayer.createBot({
  username: "chatterbox",
  viewDistance: "tiny",
});
```

Which means that in order to start them, it's needed to add the host and post in the code. Git is then telling us that the file change and all, not practical.

I think it would be better to have something like this in all the examples : 
```js
if(process.argv.length!=4)
{
	console.log("Usage : node example.js <host> <port> <name>");
	process.exit(1);
}
var bot = mineflayer.createBot({
	username: process.argv[4],
	verbose: true,
	port:parseInt(process.argv[3]),
	host:process.argv[2]});
```

What do you think ?

**Comment by demipixel** [comment]
I approve, but maybe also add [password]?

**Comment by roblabla** [comment]
:+1:

**Comment by rom1504** [comment]
Ok I'll do a PR for this. Yeah I'm ok with [password].
