### ISSUE TITLE
Guys... We didn't parse.

### ISSUE THREAD

**Issue by demipixel** [andrewrk/mineflayer#206]
The bot will emit 'login' but after just spams 4-8 times:

DID NOT PARSE THE WHOLE THING!
DID NOT PARSE THE WHOLE THING!
DID NOT PARSE THE WHOLE THING!
DID NOT PARSE THE WHOLE THING!
(Sometimes after a few minutes it does some more)

What a great error. I don't know what is emitting it. I've tried searching it up in minecraft-protocol or mineflayer on git to see if it could find in code where it was added but I can't find anything. 'Login' is emitted but 'Spawn' is not. I recieve no errors from the 'err' event.

**Comment by rom1504** [comment]
What server are you using ? I'm not getting these errors...

**Comment by roblabla** [comment]
Woops, that's a node-minecraft-protocol debug message I forgot to remove ^^'

**Comment by rom1504** [comment]
Yeah but it shouldn't happen, isn't it ?

**Comment by roblabla** [comment]
@rom1504 yup, it probably means @demipixel is connecting to a server running the wrong version. Either that, or there's a bug in the protocol, but that seems unlikely to me, I checked almost everything...

**Comment by demipixel** [comment]
I am attempting to connect to a 1.8 server (is that the wrong version?). The two things that happen are either THAT or:

return entity.username.toLowerCase() === filter.toLowerCase();
TypeError: Cannot call method 'toLowerCase' of undefined

So usually it either can't find an entity's username or it just can't parse some of the data...

**Comment by roblabla** [comment]
@demipixel sorry for the late reply,l was gone most of the week-end. Could you set the "NODE_DEBUG" environment variable to mc-proto before launching the script, and pastebin the output ? This will enable node-minecraft-protocol's debug outputs, which should help me debug the issue

**Comment by rom1504** [comment]
Also about the username problem : I think it may have been fixed by one of the last commits, so don't forget to git pull before you try again.

**Comment by demipixel** [comment]
@roblabla is NODE_DEBUG in the console or in the script? Either way, I tried both and didn't see any changes in the output... This is the error I'm getting now (after update):

http://hastebin.com/onumubires.xml
"Logged in" on login, "Spawned" on spawn.

**Comment by roblabla** [comment]
export NODE_DEBUG="mc-proto" in your console @demipixel

**Comment by roblabla** [comment]
You should git pull the mineflayer repo, lots of updates. I think that issue has been fixed recently.

**Comment by demipixel** [comment]
@roblabla http://hastebin.com/ibafizohox.vbs

I forked but I've been doing 'git fetch upstream/master' then merging but it says it's already up-to-date.

**Comment by rom1504** [comment]
@demipixel I think this is the same problem as #213
