### ISSUE TITLE
Fix moving

### ISSUE THREAD

**Issue by rom1504** [andrewrk/mineflayer#209]
Currently the bot is flying and cannot move : none of the commands to move of jumper.js have any result (no crash though)

**Comment by rom1504** [comment]
Setting entity.position.y=80; directly in sendPositionAndLook doesn't make any difference at all either.

Is there some kind of security against teleporting and unnatural movements now ? (ie an other place we need to send the position)

**Comment by rom1504** [comment]
I forgot to remove the "+ entity.height" in sendPositionAndLook so the y was wrong since the login and the server was ignoring every position sent by the client. Now tp seems to work.

**Comment by rom1504** [comment]
So, this code https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/physics.js#L102 should handle falling.
Somehow it doesn't ?

**Comment by rom1504** [comment]
adding  console.log(block); at https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/physics.js#L188 shows that blockAt doesn't seem to work... (it sees rock instead of air below him)

**Comment by rom1504** [comment]
so, after some experimenting, it seems the problem is when a block change : 
* if I use tp the bot get 10 block in the air and correctly falls
* if I break a block under the bot feet, he doesn't fall (the thinks the block is still dirt)

**Comment by rom1504** [comment]
block_change packet changed ((x,y,z) --> location) but changing that doesn't seems enough, I think there may be a problem in updateBlock

**Comment by rom1504** [comment]
Add
```js
var newBlock=blockAt(point);
if(type!=newBlock.type) console.log("Fail in "+point+" : "+newBlock.type+"!="+type);
```
at https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/blocks.js#L151 to check if updateBlock works (it doesn't currently)

**Comment by roblabla** [comment]
So either updateBlock or blockAt is broken (we don't actually KNOW if blockAt does really work currently, do we ?)

**Comment by rom1504** [comment]
@roblabla well I'm pretty sure blockAt works since the bot correctly detect air below him if I use tp (it does y+=10), but if a block change, blockAt still return stone so I think that's due to updateBlock.

**Comment by rom1504** [comment]
now working
