### ISSUE TITLE
Create Gitter?

### ISSUE THREAD

**Issue by demipixel** [andrewrk/mineflayer#212]
For those of you who don't know (even though I'm sure most of you do). I don't think you guys need convincing but I'll try anyways...

Gitter is a chat room. Every channel is linked to a repository, and there are additionals features (ex: typing #200 would link to the issue, pasting code formats correctly, etc)
It would really help for quick chats to avoid creating an "issue", or long chats to discuss anything necessary.

https://gitter.im/

**Comment by roblabla** [comment]
We had a discussion about this, and I think we should make node-minecraft-protocol and mineflayer share the same gitter room. I'll bring up a PR to add a Gitter chat button.

**Comment by roblabla** [comment]
This is fixed. We use node-minecraft-protocol's gitter room to avoid segmenting the community.
