### ISSUE TITLE
player_info not sent before named_entity_spawn?

### ISSUE THREAD

**Issue by demipixel** [andrewrk/mineflayer#213]
So I added some stuff manually that was in a pull request but hasn't been accepted yet. From trying to log into a specific server (obviously needs more testing), I found that there was a player_info missing. I got:

Item:  { UUID: [ 527226816, 3711314700, 2790224496, 2516429248 ],
  gamemode: 0 }   (search for 'player_info' event in plugins/entities.js)

The action was 1, therefore updating the gamemode (we don't do anything yet) of a player who we never got an action 0 for (new player). This meant by the time it got to receiving the named_entity_spawn, it tried to set the entity of a player we never created.

The protocol says player_info is ALWAYS sent before named_entity_spawn. What's happening? And if we can't fix it, should we just create a nameless player?

**Comment by rom1504** [comment]
I think https://github.com/andrewrk/mineflayer/pull/225 fixes that.

**Comment by demipixel** [comment]
Okay, so this issue is basically bukkit. There's a quick and dirty fix to it, but overall we'll just avoid it since we've rarely supported bukkit. Should we still add the dirty fix?

**Comment by roblabla** [comment]
I think bukkit support is pretty important. how dirty is the dirty fix ?

**Comment by rom1504** [comment]
So this is not fixed by #225 ?
The same thing is still happening ?

**Comment by rom1504** [comment]
http://wiki.vg/Protocol#Spawn_Player says player_info should always be sent *before* named_entity_spawn

What do you think about ignoring named_entity_spawn if bot.uuidToUsername[packet.playerUUID] is undefined ?

**Comment by demipixel** [comment]
@rom1504 I saw that and that's why I posted it. That was my dirty fix, ignore it. But there must be SOME reason it's getting sent, right?.... RIGHT?!?

**Comment by rom1504** [comment]
Well I don't know if we want to try to guess and support what the bukkit dev thoughts when implementing this. It might just be a bug in bukkit.
I think we should try ignoring  named_entity_spawn in that case and see if that works.
