### ISSUE TITLE
Inventory.js should be refactored

### ISSUE THREAD

**Issue by rom1504** [andrewrk/mineflayer#223]
That file has currently 1045 lines, this is way too much.

But sadly this is not the only problem, many function are imbricated making the scope of variables hard to figure out, the callbacks are hard to understand, and it handles too many thing (all the window related items, and their actions).

So I think we should either (or both) : 
* cut that file into several files
* refactor it to make it smaller and easier to read

**Comment by demipixel** [comment]
Maybe separate out crafting table from it? That would take out a chunk. Other categories?

**Comment by rom1504** [comment]
So, I think this should be like that : 
* a small inventory.js containing clickWindow, storing the slots
* a craft.js handling the craft grids using the Inventory defined in inventory.js
* a chest.js handling the chest
* ...

I think this issue is really important, because unless we fix it, each modification of inventory.js takes 10 times too long than it should.

**Comment by rom1504** [comment]
craft.js : done in 2c35ebc4d1ac82b8dae32174a4065d7dc5c46633

**Comment by rom1504** [comment]
Ok 57f83b3a874c6fcebc9ecc37311c2656d71c36ca basically solves this issue.

inventory.js is now only 448lines.

What needs to be done : put the new inventory files in a lib/plugins/inventory dir. I tried this and was unable to make it work, if someone knows how, please tell me (how make a PR / commit).

**Comment by rom1504** [comment]
Also see if it would be possible (and would make sense) to get the specific window stuff out of https://github.com/andrewrk/mineflayer/blob/master/lib/windows.js#L264 and "merge" these files with the corresponding one in plugins/ .

**Comment by rom1504** [comment]
For example chest is now handled in lib/chest.js , lib/plugin/chest.js and lib/windows.js#275.
See how to improve that design.

**Comment by thejoshwolfe** [comment]
> What needs to be done : put the new inventory files in a lib/plugins/inventory dir.

Why does that need to be done? The directory structure of the code is functionally significant in https://github.com/andrewrk/mineflayer/blob/master/index.js#L6 , so moving plugins will require code updates to find them. Is there something wrong with keeping all the plugins in one big plugin directory?

Some (myself, for example) would argue that keeping files together in a big directory makes them easier to navigate, search, work with, etc. Is there a functional reason to make an inventory directory?

**Comment by rom1504** [comment]
I know we'd need to change a bit index.js to include plugins recursively, but that doesn't seem impossible looking at https://www.npmjs.com/package/requireindex

Why I want to make an inventory directory : we now have 7 inventory-related "plugins" : chest.js, craft.js, dispenser.js, enchantment_table.js, furnace.js, inventory.js and simple_inventory.js. And I think it would be nice to be able to find these inventory-related plugins without reading the whole list of files in plugins/ (as I just did to make that list). I also think it doesn't make a lot of sense to mix them with mostly unrelated plugins like physics.js.
The third reason is chest.js, craft.js, dispenser.js, enchantment_table.js, furnace.js and simple_inventory.js use stuff exported in inventory.js so it makes sense to put them together.

**Comment by rom1504** [comment]
On another note : 
I believe even though I already made inventory.js go from 1000 lines to 400, it still contains stuff that don't belong there, including : 
* activateItem https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/inventory.js#L26
* deactivateItem https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/inventory.js#L37
* activateBlock https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/inventory.js#L96
* placeBlock https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/inventory.js#L218

I'm not sure yet where they should go but I don't think they belong in inventory.js. Inventory.js just be about just : open, handling and closing windows.

**Comment by rom1504** [comment]
I think we also should see if lib/plugins/furnace.js can go in lib/furnace.js or the other way round. (same thing for chest, enchantment_table,...)

**Comment by rom1504** [comment]
Well actually I think that's enough refactoring for now, each inventory related file is easy enough to understand. We can reorganize the files in plugins/ if needed later in an other issue.
