### ISSUE TITLE
Make a different repo for the enums ?

### ISSUE THREAD

**Issue by rom1504** [andrewrk/mineflayer#231]
I think the enums can be used by several projects, which mean these projects could also contribute to updating them.

Is that a good idea ?

**Comment by Gjum** [comment]
+1 for all the custom [clients](http://wiki.vg/Client_List) and [servers](http://wiki.vg/Server_List) out there.
Special thought would have to be put on the format though, regarding implementation in different languages.

**Comment by roblabla** [comment]
The current format is JSON, no ? If so, there shouldn't be any problems.

**Comment by rom1504** [comment]
Yeah, but maybe we could add some doc explaining what's in the format in that repo.

**Comment by Gjum** [comment]
Currently metadata is not represented in in/outShape, so there might be problems for shapes like stonebrick vs. smooth andesite, where the recipes and outcome have the same item ID.

**Comment by rom1504** [comment]
So, how would that repo be named ?
I think some parts of mineflayer would belong there too, at least everything in the bin/ folder  (it contains extractor/checker for the enums) but maybe there are other related files elsewhere, I'm not sure.
I guess it would have a package.json and be on npm.
So it would be fairly easy to use from node.js (it would become a dependency of mineflayer)

And I think other projects (not node.js) might use it as a git submodule ?

**Comment by rom1504** [comment]
I'm thinking "minecraft-data" might be a good name. Should I create it in my namespace (rom1504/) ?

I'm not sure the extractors (bin/) should be in that repo or not : they aren't actually needed for other projects (and even for mineflayer once the extraction is done), so : either they should stay in mineflayer, either we could make a "node-minecraft-data-extractors" repo or something.

**Comment by Gjum** [comment]
The extractors are not needed when dealing withthe etracted data, but when tne data becomes out of date, they will be useful for keeping up, e.g. when we do not have time to udate the repo ourselves.
It's also good for working together to improve the scripts.

**Comment by rom1504** [comment]
Yeah ok, I agree it's better not too have too many repos.
So I'm creating that there https://github.com/PrismarineJS/minecraft-data (not done yet)

**Comment by thejoshwolfe** [comment]
what about putting the data in node-minecraft-protocol?

**Comment by Gjum** [comment]
The data is not dependent on any code in node-minecraft-protocol.
That would also require other projects that use the data as a Git submodule to clone the entire node-minecraft-protocol codebase only for the minecraft data.

**Comment by demipixel** [comment]
@thejoshwolfe There are other clients out there other than mineflayer or node-minecraft-protocol that could want to use this.

**Comment by roblabla** [comment]
such data doesn't belong to the protocol anyway. I'd like to keep the protocol data-agnostic (although some amount of data has been starting to creep into the code, due to how mojang handles some stuff).
