### ISSUE TITLE
Add circle ci for test.js

### ISSUE THREAD

**Issue by rom1504** [andrewrk/mineflayer#232]
Just like https://github.com/PrismarineJS/node-minecraft-protocol

**Comment by rom1504** [comment]
Everything is ready for circle ci, it just needs to be enabled on http://circleci.com . Can you do it @andrewrk ?

**Comment by andrewrk** [comment]
ok I think I did it. did I do it right?

**Comment by rom1504** [comment]
@andrewrk Yeah it's working, thanks. (2 tests are still failing (see https://github.com/andrewrk/mineflayer/issues/180#issuecomment-84554711) but that's "normal")
