### ISSUE TITLE
support minecraft_server

### ISSUE THREAD

**Issue by thejoshwolfe** [andrewrk/mineflayer#233]
It seems most developers here are using the vanilla Minecraft client, and clicking "Open to LAN". For example, the reported progress in https://github.com/andrewrk/mineflayer/issues/180 indicates support for the above.

If you try to run the vanilla `minecraft_server.1.8.3.jar`, many things don't work anymore, such as opening chests. This issue is to keep the minecraft_server support caught up.

Known issues:

 * activating a chest block doesn't get an Open Window response. (see https://github.com/andrewrk/mineflayer/pull/166#issuecomment-84721979 )
 * Any change to the world isn't noticed by bots. (try the digger example)

**Comment by rom1504** [comment]
:+1: I've been trying everything thinking "Open to LAN" would be the same thing as the minecraft server.

**Comment by demipixel** [comment]
I'm definetely getting different results in LAN. LAN let's digger build and mine whereas my server doesn't. Then again, [LAN has its own problems for digger.js](https://www.youtube.com/watch?v=c193oELbvvc).

**Comment by rom1504** [comment]
@demipixel yeah apparently even "open to lan" doesn't work for you, which I don't understand because it works for me...

**Comment by demipixel** [comment]
@rom1504 Yeah, @thejoshwolfe is stating one of the problems is not correctly tracking the blocks, which is what looks like happens in the video.

**Comment by rom1504** [comment]
So indeed I just tested, it seems to be pretty broken using minecraft_server...

**Comment by rom1504** [comment]
So I checked using chatterbox.js : blockUpdate isn't emitted for close (add a `if(point.position.x<100 && point.position.x>90)` ) block update.

**Comment by rom1504** [comment]
So the problem was indeed there : https://github.com/PrismarineJS/node-minecraft-protocol/pull/139 fix building, falling and digging in mineflayer.

**Comment by rom1504** [comment]
checked : 
* [x] inventory.js : list, toss, craft, equip, unequip
* [ ] chest.js : still doesn't work

**Comment by rom1504** [comment]
Ok I just checked chest again and it somehow works, can somebody checks it actually works ?
Since I didn't do anything to fix it I'm a bit surprised...

**Comment by rom1504** [comment]
So, I'm not getting any particular problems in minecraft_server anymore (except the ones that aren't fixed in #180 )

**Comment by thejoshwolfe** [comment]
Did you try positive and negative x/z coordinates? Wasn't there a problem with signed vs unsigned binary packing?

**Comment by thejoshwolfe** [comment]
everything in my superflat.js test is working on a minecraft_server, including digging, placing, and using chests. This issue seems fixed.
