### ISSUE TITLE
Breaking API

### ISSUE THREAD

**Issue by thejoshwolfe** [andrewrk/mineflayer#236]
I'd like to break the api of mineflayer to implement new features and clean up some old code. should I be concerned about compatibility with any specific users? I'm looking at https://github.com/Darthfett/Helperbot for starters (as I jave a vested interest in the project).

**Comment by roblabla** [comment]
Depends on where you break API. The API seems flexible enough as it stands, do you have any specific places where you with to break API compat ?

I think breaking API in general is OK, so long as the steps to fix user code is clearly documented somewhere, and semver is followed (bump major).

**Comment by Darthfett** [comment]
Not sure that I matter, but being that I own Darthfett/Helperbot, I am watching with interest.  What APIs are we concerned about here?

The physics updates would be a pretty large setback, as it would take some time to re-implement physics.  However, Helperbot isn't exactly an active project right now.

**Comment by thejoshwolfe** [comment]
Specifically, I'd like to stop emitting `setWindowItems:0` and `setSlot:0` when the inventory updates. I'd instead like to publish a unified `inventoryUpdate` or perhaps `windowSlotsUpdate`. I ran into this lack of feature immediately when I tried to write a test for #203 and found that there was no good way to know when a `/give` command had completed.

In general, I think it's an antipattern to emit events only meant to be listened for in the same file. It may be assumed that `setWindowItems:0` is a "private event" since it's not in the API docs, but It's an encapsulation leak to allow even the possibility of client's thinking that listening to `setWindowItems:0` is how they are supposed to listen for inventory updates. I know there are a lot of different users of mineflayer out there, and having a list of all of them to search for "setWindowItems:" would put my mind at ease.

Perhaps I'm being too pedantic about trying not to break the API users' code.

**Comment by Darthfett** [comment]
I think that mineflayer is already providing a layer of abstraction on top of the inventory updates, so that helperbot is not depending on most of those events.  For example, https://github.com/Darthfett/helperbot/blob/master/lib/plugins/list.js just looks at the current inventory, which is automatically kept up-to-date in mineflayer.

I would be all for an API that is simpler, and I don't think it would be too much trouble to fix scripts in helperbot.

**Comment by roblabla** [comment]
@Darthfett but there's no way to know _when_ the inventory updates. @thejoshwolfe if it's not mentioned in the API docs, then it's OK to break as it doesn't belong to the public API. I also agree private events are bad, we could create a separate, private EventEmitter and use it to emit private events if it is really necessary.

**Comment by andrewrk** [comment]
If it's not documented in https://github.com/andrewrk/mineflayer/blob/master/doc/api.md then it's not even an issue to change API.

**Comment by thejoshwolfe** [comment]
Ok, I didn't end up needing to break the api afterall. It sounds like the answer to my original question is "don't break the api", which is a fine answer.

Also, I think this kind of discussion issue should really be held in the gitter chat. (didn't think of that when I opened this.)

**Comment by roblabla** [comment]
I think this kind of meta-issue is fine t have in github issues, as it helps keep track of previous discussion on this matter for future reference.
