### ISSUE TITLE
External test

### ISSUE THREAD

**Issue by rom1504** [andrewrk/mineflayer#239]
Tracking progress on externalTest.js.
Currently it tests : 
* [x] digging
* [x] chests
* [x] crafting
* [ ] crafting every recipe (if possible ?)
* [x] place and dig every diggable block

I think it might be a good idea to put the tests in several files since it has already 343 lines with only 2 kinds of tested things.

**Comment by thejoshwolfe** [comment]
> several files

Agreed. Then progress could be tracked by looking at the list of files :) The test so far is lending itself nicely to a framework and a list of tests that use the framework, so the file separation will be pretty intuitive.

**Comment by rom1504** [comment]
It would be really nice to have a test for crafting, having to see this kind of issue #244 manually when testing rbot is really not great.
I wonder how much time the test would take for crafting every recipe (giving himself the needed items by the creative api)

**Comment by roblabla** [comment]
If you look at what's under circle.yml, you'll notice that the client tests aren't run on it. So tests based on minecraft_server.jar aren't actually run.

**Comment by rom1504** [comment]
Oh right. I think it would be possible to wget the .jar to test it though, I'll try that.

**Comment by rom1504** [comment]
node-minecraft-protocol now tests that, so we might just do the same here (https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/circle.yml#L11)

**Comment by rom1504** [comment]
now run automatically with circle ci (see 1f0fcf64f86f638d76e856f527e79586d1bc08b3) and ported to mocha (also divided into several files)

**Comment by rom1504** [comment]
How to add a test now : 
* create a file in https://github.com/andrewrk/mineflayer/tree/master/test/externalTests (look at https://github.com/andrewrk/mineflayer/blob/master/test/externalTests/digAndBuild.js for an example)
* require it there https://github.com/andrewrk/mineflayer/blob/master/test/superflat.js#L6
* use it there https://github.com/andrewrk/mineflayer/blob/master/test/superflat.js#L69

**Comment by rom1504** [comment]
see https://github.com/andrewrk/mineflayer/blob/master/test/externalTest.js#L17 if you want to use a server you already started instead of automatically starting one.

**Comment by rom1504** [comment]
@thejoshwolfe I'm not exactly sure why you need to fly for the dirtCollectTest https://github.com/andrewrk/mineflayer/blob/master/test/externalTests/digAndBuild.js#L8 ?
Maybe this should go into beforeEach (https://github.com/andrewrk/mineflayer/blob/master/test/externalTest.js#L57) or before (https://github.com/andrewrk/mineflayer/blob/master/test/externalTest.js#L31) ?

**Comment by thejoshwolfe** [comment]
I wanted to test the falling physics and how falling interacted with a newly placed and destroyed block. I could have jumped, i suppose, but flying seemed less sensitive to the subtle implementation of the jumping physics.

i don't think it's appropriate to do it for every test.

**Comment by rom1504** [comment]
Oh ok.
I added a test for crafting, it only tests crafting 1 log into wood though, not every recipe.

**Comment by rom1504** [comment]
I think the info on how to add a test (https://github.com/andrewrk/mineflayer/issues/239#issuecomment-87506334) should probably go into a doc/contribute.md.

**Comment by rom1504** [comment]
I think what would be nice is having tests to cover all that's needed for examples/ so we don't have to check manually (https://github.com/andrewrk/mineflayer/issues/180) that the examples works again.

**Comment by rom1504** [comment]
I added a test to check if mineflayer can dig every block.
Some block correctly cannot be placed, but placing a block is broken for some blocks. See the detail there https://github.com/andrewrk/mineflayer/blob/master/test/externalTests/digEverything.js#L8

The test takes 20min so it's not enabled in circle ci.

**Comment by rom1504** [comment]
I added some info on how to create a test there https://github.com/andrewrk/mineflayer/blob/master/doc/contribute.md#creating-an-external-test and created a new issue for crafting every recipe there https://github.com/andrewrk/mineflayer/issues/274

So I think this testing framework is in a decent state, what needs to be done is adding more tests, that can be handled in other issues.
