### ISSUE TITLE
Script Immediately exits

### ISSUE THREAD

**Issue by mdobson** [andrewrk/mineflayer#242]
I have been having trouble with the mineflayer library. The script seems to immediately exits and does nothing with my server.

I have a boot2docker instance running minecraft 1.8.1 in a container. Here is my script.

The connect and end events fire.

```javascript
var mineflayer = require('mineflayer');

var bot = mineflayer.createBot({
  host: '192.168.59.103',
  port: 25565,
  verbose: true
});

bot.on('login', function() {
  console.log('login'); 
});

bot.on('connect', function() {
  console.log('connect');  
  console.log(arguments);
  bot.on('chat', function(username, message) {
    if(username === bot.username) return;
    bot.chat(message);  
  });
  bot.on('error', function(err) {
    console.log(err);
  });

  bot.on('end', function() {
    console.log('end');  
    console.log(arguments);
  });
});
```

**Comment by roblabla** [comment]
If the end event fires, it means the client was disconnected from the server. Since there is no more work to be done by the nodejs VM (the socket has been closed since the server kicked you), it will quit.

**Comment by mdobson** [comment]
Is there a reason that it gets disconnected from the server? Any additional
configuration that is required?

-Matt

On Saturday, March 28, 2015, Robin Lambertz <notifications@github.com>
wrote:

> If the end event fires, it means the client was disconnected from the
> server. Since there is no more work to be done by the nodejs VM (the socket
> has been closed since the server kicked you), it will quit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andrewrk/mineflayer/issues/242#issuecomment-87233411>.
>


-- 
*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee>

**Comment by rom1504** [comment]
How did you install mineflayer ?

**Comment by mdobson** [comment]
Installed via npm on an OSX system.

-Matt

On Saturday, March 28, 2015, Romain Beaumont <notifications@github.com>
wrote:

> How did you install mineflayer ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andrewrk/mineflayer/issues/242#issuecomment-87241318>.
>


-- 
*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee>

**Comment by demipixel** [comment]
Have you tried any of the other examples?

**Comment by mdobson** [comment]
I have not. Is there a better example to try aside from the echo server in
the readme?


-Matt
On Saturday, March 28, 2015, demipixel <notifications@github.com> wrote:

> Have you tried any of the other examples?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andrewrk/mineflayer/issues/242#issuecomment-87254887>.
>


-- 
*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee>

**Comment by rom1504** [comment]
`Installed via npm on an OSX system.`
so you did do `npm install git://github.com/andrewrk/mineflayer.git#master` ?
`npm install mineflayer` won't get you the last version.

**Comment by mdobson** [comment]
I went off the registry. I'll try using repo based install.

On Saturday, March 28, 2015, Romain Beaumont <notifications@github.com>
wrote:

> Installed via npm on an OSX system.
> so you did do npm install git://github.com/andrewrk/mineflayer.git#master
> ?
> npm install mineflayer won't get you the last version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andrewrk/mineflayer/issues/242#issuecomment-87258505>.
>


-- 
*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee>

**Comment by demipixel** [comment]
Yes, there is an "examples" folder. I'm sure this isn't your problem, but once you get it fixed, try running some of those. MOST work :P

**Comment by rom1504** [comment]
So, this issue was about an old mineflayer version (which obviously doesn't work on 1.8 servers), closing.

**Comment by cookiedragon234** [comment]
I am having this problem with node 14.3.0 and mineflayer 2.15.0, I execute [echo.js](https://github.com/PrismarineJS/mineflayer/blob/master/examples/echo.js) and it simply exits without printing any output whatsoever

**Comment by rom1504** [comment]
Can you try again ?

**Comment by cookiedragon234** [comment]
Sorry, I forgot to bind the “kick” event, my bad!
