### ISSUE TITLE
Document and standardize Danger-Zone API

### ISSUE THREAD

**Issue by roblabla** [andrewrk/mineflayer#246]
We currently have a bunch of functions exposed but not documented, which are part of what we call the "Unstable API". 

In order to make it very clear which functions are expected to be stable and frozen, and which functions can change in the future, without relying on the doc, we might want to follow a function name convention, such as prefixing an underscore. 

An instance of such an existing api : bot.client.

We could then proceed to document useful parts of the "unstable API", clearly stating it is part of a danger-zone. For instance, deathcap wishes the raw "Column"s to be directly exposed in order to loop over them. This is clearly useful, but also unstable. If we expose columns into a documented "Unstable API", we can relay the information to the user that this function is to be used with caution.

**Comment by rom1504** [comment]
Related : https://github.com/andrewrk/mineflayer/issues/156#issuecomment-87322503

**Comment by roblabla** [comment]
Moving inventory items is a high-level action that should be expected to remain accross minecraft version (Like, if mojang prohibited movement in the inventory, IDK wtf they're doing...). So I think they would be stable API.
