### ISSUE TITLE
arm_animation being sent with too many parameters

### ISSUE THREAD

**Issue by Gjum** [andrewrk/mineflayer#269]
Currently, when swinging the arm, the mineflayer client sends [more data](https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/inventory.js#L100-L101) than [necessary](http://wiki.vg/Protocol#Animation_2). This might cause a problem with "non-notch" server implementations, but maybe this data is just ignored when packing the packet.

The cause for this might be that the [*clientbound* animation packet](http://wiki.vg/Protocol#Animation) takes this additional data and someone just confused them.

**Comment by rom1504** [comment]
Correct.
Indeed _client.write seems to be ignoring any additional field given : see https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js#L1503
Shouldn't it emit some kind of error @roblabla ?

**Comment by roblabla** [comment]
Yeah. It should emit an error when missing or additional fields are given. I'll see how to implement this.
