### ISSUE TITLE
Find a mojangson spec and complete mineflayer's parser

### ISSUE THREAD

**Issue by rom1504** [andrewrk/mineflayer#272]
For example mojangson has trailing comma, the parser (https://github.com/andrewrk/mineflayer/blob/master/lib/chat_message.js#L119) isn't handling it currently.

**Comment by rom1504** [comment]
I guess it's something like this https://github.com/Bukkit/mc-dev/blob/c1627dc9cc7505581993eb0fa15597cb36e94244/net/minecraft/server/MojangsonParser.java

**Comment by rom1504** [comment]
For example @demipixel has that problem with it :  
```js
/home/cabox/workspace/node_modules/mineflayer/lib/chat_message.js:192                                               
    throw new Error("hoverEvent 'show_item' value syntax error at index " + in                                      
           ^                                                                                                         
 Error: hoverEvent 'show_item' value syntax error at index 0: {id:1s,Damage:0s,Count:1b,tag:{display:{Name:"§r§6Class
  : Civilian",Lore:[0:"§6Last Killed: None",1:"§6Last Killer: None",2:"§6Rank: §aNovice-III",3:"§6§6Elo Rating: 1000",
  ],},},}                                                                                                             
    at syntaxError (/home/cabox/workspace/node_modules/mineflayer/lib/chat_message.js:192:11)                       
    at parseDict (/home/cabox/workspace/node_modules/mineflayer/lib/chat_message.js:133:32)                         
   at parseShowItemHoverEventValue (/home/cabox/workspace/node_modules/mineflayer/lib/chat_message.js:128:16)      
```

**Comment by demipixel** [comment]
So.

in parseShowItemHoverEventValue(string) we have a few issues. 119 of lib/chat_message.js

Firstly, string is sometimes an array, so I was doing
if (string[0]) string = string[0];
But we probably need a better way to handle it.

Secondly, it's getting stuck at "72" now which is the start of Lore:
Lore:[0:...]
AKA I don't know if we handle arrays in their "custom js" but it doesn't look like it.

Rather than manually parsing, could we try and FIX the json, then parse that rather than writing our own?

**Comment by rom1504** [comment]
> Rather than manually parsing, could we try and FIX the json, then parse that rather than writing our own?

That's what we were doing before @thejoshwolfe created that parser. I think it's better to have an actual parser, trying to transform mojangson to make it look "right" is probably going to break.

**Comment by thejoshwolfe** [comment]
Transforming it into something else and parsing it directly are the same problem. For both approaches, you need to know the language you're trying to read. Making a direct parser is actually the simplest approach, in my opinion. Sure it looks scary, if you're not used to reading recursive parsers, but it actually is the most direct and minimal approach to the problem.

Making a translator, like we used to have, is much more difficult than it sounds, and yes, it was broken before I replaced it with the direct parser.

**Comment by rom1504** [comment]
so I just fixed @demipixel example, the parser now handles : 
* trailing comma
* "indexed" array ( [0:value1,1:value2] )

**Comment by rom1504** [comment]
More information on mojangson : see https://github.com/drXor/ScalaNBT and :
> 21:03 <+XorBoole> it's json with the following exceptions:
>21:04 <+XorBoole> trailing commas are allowed in arrays and objects; numbers followed by b, s, L, f, d are bytes, shorts, longs, floats, and doubles, respectively; arrays can contain only one type; key names don't require quotes

**Comment by rom1504** [comment]
I put the parser in its own file, and put the tests in internalTest.js.

So I think we are handling everything. I'd prefer the parser to be written with something like jison and maybe it should be in its separate repo but we can do that later if needed.

**Comment by rom1504** [comment]
Well mojangson is a superset of json (http://www.json.org/).
That means numbers are not just integers. That should probably be fixed, but I don't really want to parse more complicated numbers manually, I think I'll do a parser using jison later.
