### ISSUE TITLE
Players list just keeps growing.

### ISSUE THREAD

**Issue by AlexKvazos** [andrewrk/mineflayer#280]
It seems like the player list just keeps getting populated but when a user leaves, it is not removed from the players list map. Is it supposed to be like that or is there a possible solution?

**Comment by rom1504** [comment]
No it should be removed from the list (https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/entities.js#L356).

That sounds like a bug.

**Comment by AlexKvazos** [comment]
Yeah, I just tried on a vanilla 1.8.4 server and the players are not getting removed from the list.

**Comment by AlexKvazos** [comment]
https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/entities.js#L356

`item.name` appears to be undefined.
