### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Shadowwolf97** [andrewrk/mineflayer#283]
There is no license present within the GitHub project.

**Comment by demipixel** [comment]
That's so we can sue whoever tries to use it.

**Comment by rom1504** [comment]
There is : MIT
It's in the package.json
Maybe it should also be on the readme ?

**Comment by Shadowwolf97** [comment]
Oh yeah I see it now. Most people just include them in the root of the repository.

**Comment by roblabla** [comment]
The ideal way is to have a "LICENSE.md" file with the complete license, and optionally a link to the readme.
