### ISSUE TITLE
Can't install mineflayer

### ISSUE THREAD

**Issue by hugo4715** [andrewrk/mineflayer#298]
When I use the "npm install mineflayer", It tell me that:

npm http GET https://registry.npmjs.org/mineflayer

npm ERR! Error: failed to fetch from registry: mineflayer
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /root/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.18.11+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "mineflayer"
npm ERR! cwd /root
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: mineflayer
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm not ok

I don't know if I'm doing something wrong.

**Comment by roblabla** [comment]
That version of node is absurdly old. You should really update nodejs to _at least_ 0.10.

http://stackoverflow.com/a/21715730/867923 : 

> It looks like that version of npm isn't supported any more, updating node (and npm with it) resolved the issue.
> sudo apt-get purge nodejs npm

**Comment by hugo4715** [comment]
oh, thank, I was thinking that debian repos were up to date 
I'm updating :)

**Comment by rom1504** [comment]
So, I guess that fixed your problem !
