### ISSUE TITLE
Unable to toss multiple stacks in the same function

### ISSUE THREAD

**Issue by cartycrabber** [andrewrk/mineflayer#307]
I have a function that looks like this: 

```javascript
function prepareInventory() {
        bot.tossStack(bot.inventory.items()[0], function(error) {
          console.log(error);
        });
        bot.tossStack(bot.inventory.items()[1], function(error) {
          console.log(error);
        });
        bot.tossStack(bot.inventory.items()[2], function(error) {
          console.log(error);
        });
}
```

Basically what it attempts to do is toss the first three stacks in the items array. What actually happens is it only tosses the third stack.

For trouble shooting I've added a function to log every change in the inventory, so we can see what happens. It looks like this:

```javascript
bot.inventory.on('windowUpdate', function(slot, oldItem, newItem) {
  if(oldItem && newItem) {
    console.log(oldItem.name + " in slot " + slot + " replaced by " + newItem.name);
  }
  else if(oldItem) {
    console.log(oldItem.name + " in slot " + slot + " removed");
  }
});
```

I ran this with some stone brick, some dirt, and some wool. Here is the output in the console, undefined being the error callback. In game, the wool is what ended up being tossed.
```
stonebrick in slot 36 removed
dirt in slot 37 replaced by stonebrick
wool in slot 38 replaced by dirt
undefined
undefined
undefined
```

What it looks like is happening to me is it picks up the first item that it is instructed to toss, but instead of actually tossing it, it appears that it just clicks on the slot of the next item it was instructed to toss. Is there a known work around for this? If not, will there be a possible fix? I will poke around the source myself to see if I can find anything.

Not sure if I worded this to be as clear as possible, I'm writing this pretty late. I can explain anything if needed.

**Comment by cartycrabber** [comment]
So in the simple_inventory.js, I see that they way tossStack works is that it clicks the slot the item is in, and then if the callback does not return an error, it clicks outside of the inventory. The problem with this appears to be that the callback doesn't run until after the function calling tossStack completes. I have virtually no knowledge of javascript, so I'm not sure how this kind of thing works. Would it be possible to just add the line clicking outside of the window right after the line clicking on the slot, but outside of the callback? I've tested it on a server and it works, but I'm not sure what will happen under non-ideal circumstances where it runs into errors.

**Comment by cartycrabber** [comment]
I'm also finding the toss function to have similar issues. Trying to find a possible fix for that now too.

**Comment by rom1504** [comment]
You are doing it wrong.
You need to execute the next action *in* the callback.
What you are trying to do right now is to toss 3 items at the same time, which obviously isn't possible and is going to break !

**Comment by cartycrabber** [comment]
Ah, that makes a lot of sense now that you say it, thank you! Most of my experience is in Java and C# so I'm still trying to completely figure out this whole JavaScript and Node thing. 

That said, I did get tossStack to work in the way I had originally tried, but I'll see about using it properly now :P

**Comment by cartycrabber** [comment]
One more quick but completely unrelated question: Is it possible to allow the user to type into the command line while the bot is running, and to read whatever they have typed after they hit enter? To be able to provide commands from the command line. I'm positive there should be a way, but as a complete node noob, im wondering if you can just point me in the right direction

**Comment by roblabla** [comment]
@cartycrabber You'll want to look at the "readline" nodejs module https://nodejs.org/api/readline.html . You can look at [this](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_chat/client_chat.js) for an example of how to use it (search for "rl.on('chat'")
