### ISSUE TITLE
Can't place seeds

### ISSUE THREAD

**Issue by cartycrabber** [andrewrk/mineflayer#310]
I cant seem to place wheat seeds. I am most likely using something incorrectly, like last time, but I'm coming here for help.

I have the seeds equipped in hand. I call ``` /*     bot.placeBlock(bot.blockAt(bot.entity.position.offset(0, -1, 0)), vec3(0, 1, 0));``` in an attempt to place the seeds on the block I am standing on. This does nothing.

I also tried looking at the block and calling ```bot.activateItem()```, no dice.

I'm using ```bot.equip(bot.inventory.findInventoryItem(295,null), "hand");``` where 295 is the id of the wheat seeds to equip the seeds.

What am I doing wrong?

**Comment by Darker** [comment]
And is the bot visibly holding seeds? Does it swing arm when you try to place them? Do you get something in the server console?

**Comment by rom1504** [comment]
Everything that's not in that list https://github.com/andrewrk/mineflayer/blob/master/test/externalTests/digEverything.js#L7 worked the last time I tried so that's surprising.
I'll investigate.

**Comment by rom1504** [comment]
Oh but I know what's wrong : "to place the seeds on the block I am standing on".
That's not possible unless you jump before (try it with the vanilla client)

**Comment by Darker** [comment]
It's possible to place no-hitbox blocks (torch, seeds, sapligs) right under yourself.

**Comment by rom1504** [comment]
ok yeah I just tried it with torches : it works.

@cartycrabber you did use bot.equip callback right ? (see https://github.com/andrewrk/mineflayer/blob/master/doc/api.md#botequipitem-destination-callback )

**Comment by Darker** [comment]
Maybe he could just send the robot's code (unless it's confidential). It's either a strange bug or some simple mistake in his code.

**Comment by Darker** [comment]
oh wait - what about `bot.activateBlock(bot.blockAt(bot.entity.position.offset(0, -1, 0)))` while holding seeds?

And `bot.activateItem()` doesn't seem to ever do anything that purposely targets specific blocks.

**Comment by rom1504** [comment]
Ok so I just tried (after using a hoe on dirt and equipping the bot with a seed), placing a seed under the bot with placeBlock does work !

I bet the problem was you didn't use the callback of equip and hence didn't let the bot equip the seed @cartycrabber 

Reopen if you still have that issue ;)
