### ISSUE TITLE
soulsand should slows down the movement speed

### ISSUE THREAD

**Issue by rom1504** [andrewrk/mineflayer#314]
http://minecraft.gamepedia.com/Soul_Sand#Usage

"Soul sand slows the movement of any mob or player, and causes them to sink slightly into the block while walking on it. Its slowing effect is increased when placed in water, or above ice, packed ice, or slime blocks"

Need more info.
One way would be looking into minecraft decompiled code.

**Comment by rom1504** [comment]
ammar2 says it's 40% of the speed.

**Comment by rom1504** [comment]
Got to change that https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/physics.js#L18

I think it should somehow be in bot, so we can do bot.maxGroundSpeed *=0.4;

Or maybe that check (being on soulsand) should be in physics.js.

**Comment by roblabla** [comment]
Shouldn't such modifiers be in minecraft-data ?

**Comment by rom1504** [comment]
Yeah it should probably go in https://github.com/PrismarineJS/minecraft-data/issues/6
I think that's just for soulsand though ? Is there any other block that slow down the movement of the player ?

**Comment by Gjum** [comment]
Water maybe? And lava?

**Comment by Gjum** [comment]
Also cobwebs and (packed) ice

**Comment by rom1504** [comment]
Hmm yeah, but I think the condition are all different for each of those, so I'm not sure how that would fit in minecraft data, but yeah good point.

**Comment by Gjum** [comment]
Fluids and cobweb work on players inside them, ice on players above it.
With soul sand, the question is if a player is inside or above the block when affected by it, as it sinks down when standing on it.
