### ISSUE TITLE
Bot can't seem to break ores right

### ISSUE THREAD

**Issue by jcgurango** [andrewrk/mineflayer#329]
So I'm using the `block.dig` method and whenever the bot tries to dig ore (any kind of ore) it freezes up. It tries to dig it, but from what it looks like, the block is digging but never quite finishes so the bot just stands there and the callbacks are never called. It even happens with the scaffold plugin. I initially thought it had to do with the `bot.digTime` method, but changing that to return twice as long didn't work.

**Comment by rom1504** [comment]
@jcgurango current master fix digging in some server (see 2a8652e89286bd86c9a3df016c398120bf48e56e)
Try to use it instead of 0.14.0

**Comment by jcgurango** [comment]
@rom1504 Oh cool, thanks. (Haven't had a github account very long. Is it customary to say thanks in this situation?)
