### ISSUE TITLE
Health regen

### ISSUE THREAD

**Issue by unnown** [andrewrk/mineflayer#332]
There doesn't seem to be any functional health regen, even when the bot is at full health, is this something we need to call/do?

**Comment by roblabla** [comment]
Health is entirely managed by the server, the code for it can be found [there](https://github.com/andrewrk/mineflayer/blob/a768289d01e12debdf5e5a6a56afd4f88a9d43c7/lib/plugins/health.js). There's nothing much for us to do here, could you show us an example of health breaking ?

**Comment by rom1504** [comment]
Can't reproduce, feel free to reopen if you still have issues about health regen.
