### ISSUE TITLE
Whisper Event

### ISSUE THREAD

**Issue by JustinKelleher** [andrewrk/mineflayer#335]
I cannot seem to get the whisper event to work.  My current code has a near copy of the example whisper code.  I'm thinking their is a problem with the API but I'm not an expert in JavaScript.

My Code: http://pastebin.com/JdsYB9jz

**Comment by Gjum** [comment]
Mineflayer uses the `/tell` command. Is that implemented on `woodycraft.net`?

**Comment by Gjum** [comment]
Also the chat might not be parsed correctly. Does the `whisper` event get emitted, i.e. does the console print `"I received a message from ..."`? Or does the bot just not chat back?

**Comment by demipixel** [comment]
Usually these servers have custom messages. I usually had to do bot.on("message"...) (or whichever one brought back JSON or just plain text) and then regex it.

**Comment by JustinKelleher** [comment]
@Gjum WoodyCraft does support the /tell command but I don't receive the console output,

@demipixel I'll give that a try.  Thank you.

**Comment by Gjum** [comment]
@JustinKelleher also take a look at #323 #273 and maybe #175

**Comment by JustinKelleher** [comment]
@Gjum Thanks!  I'm confused on how to use the chat pattern system but I'll try it out.

**Comment by rom1504** [comment]
Yeah you might want to look at the example for chat pattern https://github.com/andrewrk/mineflayer/blob/master/examples/chatAddPattern.js

Bukkit minecraft servers use different chat plugins, so some work has to be done to parse the specific format for each server.

**Comment by Gjum** [comment]
@JustinKelleher You have that problem because mineflayer cannot parse any server's private message format, so you should listen on "message" and write your own parser.

**Comment by JustinKelleher** [comment]
@rom1504 and @Gjum Thank you for your help!

**Comment by JustinKelleher** [comment]
Why does the regex statement return the username as "null"?

https://gist.github.com/JustinKelleher/b06fb5c29e137c4284e1

**Comment by JustinKelleher** [comment]
Why does the regex statement return the username as "null"?

https://gist.github.com/JustinKelleher/b06fb5c29e137c4284e1

**Comment by rom1504** [comment]
Seems the problem was fixed in that gist, feel free to reopen if you have more problem about that !
