### ISSUE TITLE
How to make bot equip picked up item?

### ISSUE THREAD

**Issue by Minecheesecraft** [andrewrk/mineflayer#338]
I cannot seem to get my bot to pick up any items I give it. The code I am gives me an error, but I have no idea whats wrong with it..

This is the code I am trying to use.
bot.on('playerCollect', function(bot.entity, 298) { bot.equip(298, "head") } ) //Leather Cap

If this is a stupid mistake, I apologize, I am new to javascript.

**Comment by rom1504** [comment]
You can do that:
```js
bot.on('playerCollect', function(collector, collected) {
  if(collector.type === 'player' && collected.type === 'object' && collector.username == bot.username) {
    var rawItem = collected.metadata[10];
    var item = mineflayer.Item.fromNotch(rawItem);
    if(item.name=="leather_helmet")
      bot.equip(item.type,"head");
  }
});
```

**Comment by Minecheesecraft** [comment]
Oh sweet! Thank you so much!

**Comment by Minecheesecraft** [comment]
Ok, there's actually a bit of a problem with that code. If the bot picks up the leather helmet, and doesn't already have a leather helmet in its inventory it crashes. So it needs a helmet in it's inventory before it picks up another to wear it.

**Comment by rom1504** [comment]
Ah yeah, you might want to use the ["windowUpdate"](https://github.com/andrewrk/mineflayer/blob/master/doc/api.md#window-windowupdate-slot-olditem-newitem) event instead (bot.inventory.on("windowUpdate",...)

**Comment by Minecheesecraft** [comment]
Now it won't do anything.

```javascript
var mineflayer = require('mineflayer');
console.log("Equip plugin started.")
module.exports.inject = inject;

function inject(bot) {

bot.inventory.on('windowUpdate', function(collector, collected) {
  if(collector.type === 'player' && collected.type === 'object' && collector.username == bot.username) {
    var rawItem = collected.metadata[10];
    var item = mineflayer.Item.fromNotch(rawItem);
    if(item.name=="leather_helmet") bot.equip(item.type,"head");
	if(item.name=="iron_helmet") bot.equip(item.type,"head");
  }
});

}
```

**Comment by rom1504** [comment]
Well look at the doc I linked up there, the arguments of the windowUpdate event are different ;)
I'll make an example code of using that later if needed.

**Comment by Minecheesecraft** [comment]
Could you please make that example?

**Comment by rom1504** [comment]
Try this (I haven't tested it): 
```js
bot.on('windowUpdate', function(slot, oldItem, newItem) {
    if(newItem.name=="leather_helmet" && slot!=5)
      bot.equip(newItem.type,"head");
});
```
5 is for head (see https://github.com/andrewrk/mineflayer/blob/4895e4d54c406ce04d1a5cf0e678dcabcd42339b/lib/plugins/simple_inventory.js#L9)

**Comment by Minecheesecraft** [comment]
Didn't work at first, but with a small tweak it was perfect! Thank you so much!

```javascript
var mineflayer = require('mineflayer');
console.log("Equip plugin started.")
module.exports.inject = inject;

function inject(bot) {

var newItem = undefined

bot.inventory.on('windowUpdate', function(slot, oldItem, newItem) {
	if (newItem != undefined) {
    if(newItem.name=="leather_helmet" && slot!=5)
      bot.equip(newItem.type,"head");
	}
});

}
```
