### ISSUE TITLE
Bot does nothing to confirm it's still connected

### ISSUE THREAD

**Issue by Corgano** [andrewrk/mineflayer#340]
Expected behavior:
Bot is on server, the server restarts. The bot should crash or throw some kind of error
What happens:
Bot is on server, the server restarts. If the bot was idle at the time, it assumes it is still connected to the server.

Possible fix: Have the bot check for server KeepAlive packets, and if no packet was recieved within ~10 seconds? then have it disconnect / throw an error.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/306
